/*
	 * BMS_device_spec.h
	 *
	 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
	 *
	 *
	 *  Created on: 2019-06-19 13:15:23.433860
	 *      Author: Dephy Inc
	 */
	

	#define DEVICE_FIELD_COUNT 24

#define	PROTOTYPE_POS 0
#define	ID_POS 1
#define	STATE_TIME_POS 2
#define	CELLS[0].MV_POS 3
#define	CELLS[0].MAH_POS 4
#define	CELLS[1].MV_POS 5
#define	CELLS[1].MAH_POS 6
#define	CELLS[2].MV_POS 7
#define	CELLS[2].MAH_POS 8
#define	CELLS[3].MV_POS 9
#define	CELLS[3].MAH_POS 10
#define	CELLS[4].MV_POS 11
#define	CELLS[4].MAH_POS 12
#define	CELLS[5].MV_POS 13
#define	CELLS[5].MAH_POS 14
#define	CELLS[6].MV_POS 15
#define	CELLS[6].MAH_POS 16
#define	CELLS[7].MV_POS 17
#define	CELLS[7].MAH_POS 18
#define	CELLS[8].MV_POS 19
#define	CELLS[8].MAH_POS 20
#define	CELLCHARGE_POS 21
#define	CELLDISCHARGE_POS 22
#define	STATUS_POS 23


