/*
 * BMS_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *
 *  Created on: 2019-06-20 11:09:57.070180
 *      Author: Dephy Inc
 */


#ifndef BMS_DEVICE_SPEC
	#define BMS_DEVICE_SPEC
	#define DEVICE_FIELD_COUNT 25

	#define	PROTOTYPE_POS 0
	#define	ID_POS 1
	#define	STATE_TIME_POS 2
	#define	CELLS_0_MV_POS 3
	#define	CELLS_1_MV_POS 4
	#define	CELLS_2_MV_POS 5
	#define	CELLS_3_MV_POS 6
	#define	CELLS_4_MV_POS 7
	#define	CELLS_5_MV_POS 8
	#define	CELLS_6_MV_POS 9
	#define	CELLS_7_MV_POS 10
	#define	CELLS_8_MV_POS 11
	#define	BMS_STATE_POS 12
	#define	CURRENT_POS 13
	#define	TIMER_POS 14
	#define	BALANCING_POS 15
	#define	STACK_VOLTAGE_POS 16
	#define	PACK_IMBALANCE_POS 17
	#define	TEMP_0_POS 18
	#define	TEMP_1_POS 19
	#define	TEMP_2_POS 20
	#define	GENVAR_0_POS 21
	#define	GENVAR_1_POS 22
	#define	GENVAR_2_POS 23
	#define	GENVAR_3_POS 24

#endif  //BMS_DEVICE_SPEC