/*
	 * CycleTester_device_spec.h
	 *
	 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
	 *
	 *
	 *  Created on: 2019-06-19 12:06:46.330430
	 *      Author: Dephy Inc
	 */
	

	#define DEVICE_FIELD_COUNT 32

#define	RIGID_POS 0
#define	ID_POS 1
#define	STATE_TIME_POS 2
#define	ACCELX_POS 3
#define	ACCELY_POS 4
#define	ACCELZ_POS 5
#define	GYROX_POS 6
#define	GYROY_POS 7
#define	GYROZ_POS 8
#define	MOT_ANG_POS 9
#define	MOT_VEL_POS 10
#define	MOT_ACC_POS 11
#define	MOT_CUR_POS 12
#define	MOT_VOLT_POS 13
#define	BATT_VOLT_POS 14
#define	BATT_CURR_POS 15
#define	TEMPERATURE_POS 16
#define	STATUS_MN_POS 17
#define	STATUS_EX_POS 18
#define	STATUS_RE_POS 19
#define	GENVAR_0_POS 20
#define	GENVAR_1_POS 21
#define	GENVAR_2_POS 22
#define	GENVAR_3_POS 23
#define	GENVAR_4_POS 24
#define	GENVAR_5_POS 25
#define	GENVAR_6_POS 26
#define	GENVAR_7_POS 27
#define	GENVAR_8_POS 28
#define	GENVAR_9_POS 29
#define	ANK_ANG_POS 30
#define	ANK_VEL_POS 31


