/*
 * Exo_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *
 *  Created on: 2019-06-20 11:10:00.093202
 *      Author: Dephy Inc
 */


#ifndef EXO_DEVICE_SPEC
	#define EXO_DEVICE_SPEC
	#define DEVICE_FIELD_COUNT 46

	#define	RIGID_POS 0
	#define	ID_POS 1
	#define	STATE_TIME_POS 2
	#define	ACCELX_POS 3
	#define	ACCELY_POS 4
	#define	ACCELZ_POS 5
	#define	GYROX_POS 6
	#define	GYROY_POS 7
	#define	GYROZ_POS 8
	#define	MOT_ANG_POS 9
	#define	MOT_VEL_POS 10
	#define	MOT_ACC_POS 11
	#define	MOT_CUR_POS 12
	#define	MOT_VOLT_POS 13
	#define	BATT_VOLT_POS 14
	#define	BATT_CURR_POS 15
	#define	TEMPERATURE_POS 16
	#define	STATUS_MN_POS 17
	#define	STATUS_EX_POS 18
	#define	STATUS_RE_POS 19
	#define	GENVAR_0_POS 20
	#define	GENVAR_1_POS 21
	#define	GENVAR_2_POS 22
	#define	GENVAR_3_POS 23
	#define	GENVAR_4_POS 24
	#define	GENVAR_5_POS 25
	#define	GENVAR_6_POS 26
	#define	GENVAR_7_POS 27
	#define	GENVAR_8_POS 28
	#define	GENVAR_9_POS 29
	#define	ANK_ANG_POS 30
	#define	ANK_VEL_POS 31
	#define	ANK_FROM_MOT_POS 32
	#define	ANK_TORQUE_POS 33
	#define	STEP_ENERGY_POS 34
	#define	WALKING_STATE_POS 35
	#define	GAIT_STATE_POS 36
	#define	SHK_ANG_DEG_POS 37
	#define	GBL_SHNK_ANG_POS 38
	#define	DGE_STATE_POS 39
	#define	MOT_FROM_ANK_ANG_POS 40
	#define	STEP_COUNT_POS 41
	#define	TRAINING_DATA_CURRENT_STATUS_POS 42
	#define	NEED_TO_ADD_STEPS_POS 43
	#define	TRAINING_PROGRESS_POS 44
	#define	SUBSTATEDPEB42_POS 45

#endif  //EXO_DEVICE_SPEC