/*
 * flexsea_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *  Created on: 2019-05-02 16:33:47.159690
 *      Author: Dephy Inc
 */

#ifndef EXO_DEVICE_SPEC_H_
#define EXO_DEVICE_SPEC_H_

#ifdef __cplusplus
extern "C" {
#endif

const char *_rigid_fieldlabels[_rigid_mn_numFields] = {
	"rigid",
	"id",
	"state_time",
	"accelx",
	"accely",
	"accelz",
	"gyrox",
	"gyroy",
	"gyroz",
	"mot_ang",
	"mot_vel",
	"mot_acc",
	"mot_cur",
	"mot_volt",
	"batt_volt",
	"batt_curr",
	"temperature",
	"status_Mn",
	"status_Ex",
	"status_Re",
	"genvar_0",
	"genvar_1",
	"genvar_2",
	"genvar_3",
	"genvar_4",
	"genvar_5",
	"genvar_6",
	"genvar_7",
	"genvar_8",
	"genvar_9",
	"ank_ang",
	"ank_vel",
	"ank_from_mot",
	"ank_torque",
	"step_energy",
	"walking_state",
	"gait_state",
	"shk_ang_deg",
	"gbl_shnk_ang",
	"dge_state",
	"mot_from_ank_ang",
};

const uint8_t _rigid_field_formats[_rigid_mn_numFields] = {
	FORMAT_8U,
	FORMAT_16U,
	FORMAT_32U,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_32S,
	FORMAT_32S,
	FORMAT_32S,
	FORMAT_32S,
	FORMAT_32S,
	FORMAT_16U,
	FORMAT_16S,
	FORMAT_8S,
	FORMAT_8U,
	FORMAT_8U,
	FORMAT_8U,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_8S,
	FORMAT_8S,
	FORMAT_16S,
	FORMAT_16S,
	FORMAT_8S,
	FORMAT_32S,
};

uint8_t *_rigid_field_pointers[_rigid_mn_numFields] = {
	(uint8_t *)&0,
	(uint8_t *)&0,
	(uint8_t *)&rigid1.ctrl.timestamp,
	(uint8_t *)&rigid1.mn.accel.x,
	(uint8_t *)&rigid1.mn.accel.y,
	(uint8_t *)&rigid1.mn.accel.z,
	(uint8_t *)&rigid1.mn.gyro.x,
	(uint8_t *)&rigid1.mn.gyro.y,
	(uint8_t *)&rigid1.mn.gyro.z,
	(uint8_t *)&rigid1.ex._enc_ang_,
	(uint8_t *)&rigid1.ex._enc_ang_vel_,
	(uint8_t *)&rigid1.ex.mot_acc,
	(uint8_t *)&rigid1.ex.mot_current,
	(uint8_t *)&rigid1.ex.mot_volt,
	(uint8_t *)&rigid1.re.vb,
	(uint8_t *)&rigid1.re.current,
	(uint8_t *)&rigid1.re.temp,
	(uint8_t *)&rigid1.mn.status,
	(uint8_t *)&rigid1.ex.status,
	(uint8_t *)&rigid1.re.status,
	(uint8_t *)&RGD_STRUCT.mn.genVar,
	(uint8_t *)&RGD_STRUCT.mn.genVar+1,
	(uint8_t *)&RGD_STRUCT.mn.genVar+2,
	(uint8_t *)&RGD_STRUCT.mn.genVar+3,
	(uint8_t *)&RGD_STRUCT.mn.genVar+4,
	(uint8_t *)&RGD_STRUCT.mn.genVar+5,
	(uint8_t *)&RGD_STRUCT.mn.genVar+6,
	(uint8_t *)&RGD_STRUCT.mn.genVar+7,
	(uint8_t *)&RGD_STRUCT.mn.genVar+8,
	(uint8_t *)&RGD_STRUCT.mn.genVar+9,
	(uint8_t *)&RGD_STRUCT.ctrl._ank_ang_deg_,
	(uint8_t *)&RGD_STRUCT.ctrl._ank_vel_,
	(uint8_t *)&RGD_STRUCT.ctrl._ank_ang_from_mot_,
	(uint8_t *)&0,
	(uint8_t *)&RGD_STRUCT.ctrl.step_energy,
	(uint8_t *)&RGD_STRUCT.ctrl.walkingState,
	(uint8_t *)&RGD_STRUCT.ctrl.gaitState,
	(uint8_t *)&shk_ang_deg_int,
	(uint8_t *)&RGD_STRUCT.ctrl.gbl_shnk_ang,
	(uint8_t *)&dge_state,
	(uint8_t *)&mot_from_ank_ang,
};

#ifdef __cplusplus
}
#endif

#endif //EXO_DEVICE_SPEC_H_

