/*
 * SCCD_device_spec.h
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *
 *  Created on: 2019-06-20 11:10:02.106064
 *      Author: Dephy Inc
 */


#ifndef SCCD_DEVICE_SPEC
	#define SCCD_DEVICE_SPEC
	#define DEVICE_FIELD_COUNT 24

	#define	PROTOTYPE_POS 0
	#define	ID_POS 1
	#define	STATE_TIME_POS 2
	#define	CELLS_0_MV_POS 3
	#define	CELLS_0_MAH_POS 4
	#define	CELLS_1_MV_POS 5
	#define	CELLS_1_MAH_POS 6
	#define	CELLS_2_MV_POS 7
	#define	CELLS_2_MAH_POS 8
	#define	CELLS_3_MV_POS 9
	#define	CELLS_3_MAH_POS 10
	#define	CELLS_4_MV_POS 11
	#define	CELLS_4_MAH_POS 12
	#define	CELLS_5_MV_POS 13
	#define	CELLS_5_MAH_POS 14
	#define	CELLS_6_MV_POS 15
	#define	CELLS_6_MAH_POS 16
	#define	CELLS_7_MV_POS 17
	#define	CELLS_7_MAH_POS 18
	#define	CELLS_8_MV_POS 19
	#define	CELLS_8_MAH_POS 20
	#define	CELLCHARGE_POS 21
	#define	CELLDISCHARGE_POS 22
	#define	STATUS_POS 23

#endif  //SCCD_DEVICE_SPEC