/*
 * SCCD_device_spec.c
 *
 * AUTOGENERATED FILE! ONLY EDIT IF YOU ARE A MACHINE!
 *
 *
 *  Created on: 2019-06-20 11:10:02.106064
 *      Author: Dephy Inc
 */

#include "flexsea_device_spec.h"
#include "SCCD_device_spec.h"
#include "flexsea_user_structs.h"

	#define DEVICE_FIELD_COUNT 24

const char *sccd_spec_labels[DEVICE_FIELD_COUNT] = {
	"prototype",
	"id",
	"state_time",
	"cells[0].mV",
	"cells[0].mAh",
	"cells[1].mV",
	"cells[1].mAh",
	"cells[2].mV",
	"cells[2].mAh",
	"cells[3].mV",
	"cells[3].mAh",
	"cells[4].mV",
	"cells[4].mAh",
	"cells[5].mV",
	"cells[5].mAh",
	"cells[6].mV",
	"cells[6].mAh",
	"cells[7].mV",
	"cells[7].mAh",
	"cells[8].mV",
	"cells[8].mAh",
	"cellCharge",
	"cellDischarge",
	"Status",
};

const uint8_t sccd_spec_formats[DEVICE_FIELD_COUNT] = {
	FORMAT_8U,
	FORMAT_16U,
	FORMAT_32U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_16U,
	FORMAT_8U,
};
	
	FlexseaDeviceSpec fx_sccd_spec = {
			.numFields = DEVICE_FIELD_COUNT,
			.fieldLabels = sccd_spec_labels,
			.fieldTypes = sccd_spec_formats
	};

#ifndef BOARD_TYPE_FLEXSEA_PLAN

#include "sccd.h"
uint8_t *sccd_spec_variables[DEVICE_FIELD_COUNT] = {
	0,
	0,
	0,
	(uint8_t *)&cells[0].mV,
	(uint8_t *)&cells[0].dischargeMah,
	(uint8_t *)&cells[1].mV,
	(uint8_t *)&cells[1].dischargeMah,
	(uint8_t *)&cells[2].mV,
	(uint8_t *)&cells[2].dischargeMah,
	(uint8_t *)&cells[3].mV,
	(uint8_t *)&cells[3].dischargeMah,
	(uint8_t *)&cells[4].mV,
	(uint8_t *)&cells[4].dischargeMah,
	(uint8_t *)&cells[5].mV,
	(uint8_t *)&cells[5].dischargeMah,
	(uint8_t *)&cells[6].mV,
	(uint8_t *)&cells[6].dischargeMah,
	(uint8_t *)&cells[7].mV,
	(uint8_t *)&cells[7].dischargeMah,
	(uint8_t *)&cells[8].mV,
	(uint8_t *)&cells[8].dischargeMah,
	(uint8_t *)&cellCharge,
	(uint8_t *)&cellDischarge,
	(uint8_t *)&sccdStatus,
};

uint32_t *fx_dev_timestamp = &rigid1.ctrl.timestamp;
const FlexseaDeviceSpec *fx_this_device_spec = &fx_sccd_spec;
const uint8_t **_dev_data_pointers = (const uint8_t **) sccd_spec_variables;
const uint8_t *_dev_field_formats = sccd_spec_formats;

uint32_t fx_active_bitmap[FX_BITMAP_WIDTH_C];
uint16_t fx_num_fields_active = 0;

const uint8_t *_device_active_field_pointers[DEVICE_FIELD_COUNT];
uint8_t _device_active_field_lengths[DEVICE_FIELD_COUNT];

const uint16_t *read_num_fields_active = &fx_num_fields_active;
const uint8_t **read_device_active_field_pointers = (const uint8_t **)_device_active_field_pointers;
const uint8_t *read_device_active_field_lengths =_device_active_field_lengths;

void setActiveFieldsByMap(uint32_t *map)
{
	const uint8_t * dev_field_formats = fx_this_device_spec->fieldTypes;

	int i, j=0;
	for(i=0;i<DEVICE_FIELD_COUNT; ++i)
	{
		if(IS_FIELD_HIGH(i, map))
		{
			_device_active_field_pointers[j] = _dev_data_pointers[i];
			_device_active_field_lengths[j] = FORMAT_SIZE_MAP[dev_field_formats[i]];
			++j;
		}
	}

	fx_num_fields_active = j;
}

#endif // BOARD_TYPE_FLEXSEA_PLAN
